### ISSUE TITLE
Minor build system issues

### ISSUE THREAD

**Issue by sin-diesel** [SmirnovAleksandrS/Labs-toolchain#1]
- [ ] Clean repository root  from  datafiles (.csv)
- [ ] Remove binary artifacts from git repo
- [ ] CCLLVM and separate build step not required
- [ ] Please explain why `QEMU_USER` and `CFLAGS` are set with `?=` assignment, while `CC` and `CCLLVM` are set with direct assignment (`=`)

**Comment by SmirnovAleksandrS** [comment]
In last commit, I remove all datafiles from root, not them in `data` folder. Also added gitignore and removed artifacts. About CC and CCLLVM, I want to build code in one command and I don't want to transfer variable into make, but now I prepairing huge remake of this Lab and in them I don't use direct variables.
